ALTER TABLE via_bridge_tx
    DROP CONSTRAINT IF EXISTS via_bridge_tx_votable_tx_id_fkey;

ALTER TABLE via_bridge_tx
    DROP COLUMN IF EXISTS votable_tx_id;

ALTER TABLE via_bridge_tx
    ADD COLUMN IF NOT EXISTS l1_block_number BIGINT NOT NULL DEFAULT 0;

ALTER TABLE via_bridge_tx
    ADD COLUMN IF NOT EXISTS proof_reveal_tx_id BYTEA NOT NULL;

CREATE TABLE IF NOT EXISTS via_withdrawals (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridge_tx_id" BIGINT REFERENCES via_bridge_tx(id) ON DELETE CASCADE DEFAULT NULL,
    "l2_tx_hash" VARCHAR NOT NULL,
    "l2_tx_index" BIGINT NOT NULL,
    "receiver" VARCHAR NOT NULL,
    "value" BIGINT NOT NULL,
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_votable_index UNIQUE ("l2_tx_hash", "l2_tx_index")
);
