DROP TABLE via_bridge_tx;

CREATE TABLE IF NOT EXISTS via_l1_batch_bridge_withdrawals (
    "proof_reveal_tx_id" BYTEA NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS via_bridge_withdrawals (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tx_id" BYTEA NOT NULL UNIQUE,
    "executed" BOOLEAN NOT NULL DEFAULT FALSE,
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS via_withdrawals (
    "id" VARCHAR UNIQUE NOT NULL,
    "bridge_withdrawal_id" BIGINT REFERENCES via_bridge_withdrawals(id) ON DELETE CASCADE DEFAULT NULL,
    "l2_tx_hash" VARCHAR NOT NULL,
    "l2_tx_log_index" BIGINT NOT NULL,
    "receiver" VARCHAR NOT NULL,
    "value" BIGINT NOT NULL,
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);
