CREATE TABLE via_bridge_tx (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "votable_tx_id" BIGINT REFERENCES via_votable_transactions(id),
    "hash" BYTEA,
    "data" BYTEA DEFAULT NULL,
    "index" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_votable_index UNIQUE ("votable_tx_id", "index")
);

-- Migrate the bridge_tx_id to the new via_bridge_tx table
INSERT INTO via_bridge_tx ("votable_tx_id", "hash")
SELECT
    id AS "votable_tx_id",
    bridge_tx_id AS "hash"
FROM via_votable_transactions
WHERE bridge_tx_id IS NOT NULL;

-- Drop the bridge_tx_id column
ALTER TABLE via_votable_transactions DROP COLUMN bridge_tx_id;
