use crate::{
    configs::{
        base_token_adjuster::BaseTokenAdjusterConfig,
        chain::{CircuitBreakerConfig, MempoolConfig, OperationsManagerConfig, StateKeeperConfig},
        consensus::ConsensusConfig,
        da_dispatcher::DADispatcherConfig,
        fri_prover_group::FriProverGroupConfig,
        house_keeper::HouseKeeperConfig,
        prover_job_monitor::ProverJobMonitorConfig,
        pruning::PruningConfig,
        snapshot_recovery::SnapshotRecoveryConfig,
        vm_runner::{BasicWitnessInputProducerConfig, ProtectiveReadsWriterConfig},
        CommitmentGeneratorConfig, ExperimentalVmConfig, ExternalPriceApiClientConfig,
        FriProofCompressorConfig, FriProverConfig, FriProverGatewayConfig,
        FriWitnessGeneratorConfig, FriWitnessVectorGeneratorConfig, GeneralConfig,
        ObservabilityConfig, PrometheusConfig, ProofDataHandlerConfig,
    },
    ApiConfig, ContractVerifierConfig, DBConfig, EthConfig, ExternalProofIntegrationApiConfig,
    ObjectStoreConfig, PostgresConfig, SnapshotsCreatorConfig, ViaBtcSenderConfig,
    ViaBtcWatchConfig, ViaCelestiaConfig, ViaVerifierConfig,
};

#[derive(Debug, Clone, PartialEq)]
pub struct ViaGeneralConfig {
    pub postgres_config: Option<PostgresConfig>,
    pub api_config: Option<ApiConfig>,
    pub contract_verifier: Option<ContractVerifierConfig>,
    pub circuit_breaker_config: Option<CircuitBreakerConfig>,
    pub mempool_config: Option<MempoolConfig>,
    pub operations_manager_config: Option<OperationsManagerConfig>,
    pub state_keeper_config: Option<StateKeeperConfig>,
    pub house_keeper_config: Option<HouseKeeperConfig>,
    pub proof_compressor_config: Option<FriProofCompressorConfig>,
    pub prover_config: Option<FriProverConfig>,
    pub prover_gateway: Option<FriProverGatewayConfig>,
    pub witness_vector_generator: Option<FriWitnessVectorGeneratorConfig>,
    pub prover_group_config: Option<FriProverGroupConfig>,
    pub witness_generator_config: Option<FriWitnessGeneratorConfig>,
    pub prometheus_config: Option<PrometheusConfig>,
    pub proof_data_handler_config: Option<ProofDataHandlerConfig>,
    pub db_config: Option<DBConfig>,
    pub eth: Option<EthConfig>,
    pub snapshot_creator: Option<SnapshotsCreatorConfig>,
    pub observability: Option<ObservabilityConfig>,
    pub da_dispatcher_config: Option<DADispatcherConfig>,
    pub protective_reads_writer_config: Option<ProtectiveReadsWriterConfig>,
    pub basic_witness_input_producer_config: Option<BasicWitnessInputProducerConfig>,
    pub commitment_generator: Option<CommitmentGeneratorConfig>,
    pub snapshot_recovery: Option<SnapshotRecoveryConfig>,
    pub pruning: Option<PruningConfig>,
    pub core_object_store: Option<ObjectStoreConfig>,
    pub base_token_adjuster: Option<BaseTokenAdjusterConfig>,
    pub external_price_api_client_config: Option<ExternalPriceApiClientConfig>,
    pub consensus_config: Option<ConsensusConfig>,
    pub external_proof_integration_api_config: Option<ExternalProofIntegrationApiConfig>,
    pub experimental_vm_config: Option<ExperimentalVmConfig>,
    pub prover_job_monitor_config: Option<ProverJobMonitorConfig>,
    // VIA specific configs
    pub via_btc_sender_config: Option<ViaBtcSenderConfig>,
    pub via_btc_watch_config: Option<ViaBtcWatchConfig>,
    pub via_celestia_config: Option<ViaCelestiaConfig>,
    pub via_verifier_config: Option<ViaVerifierConfig>,
}

impl From<GeneralConfig> for ViaGeneralConfig {
    fn from(value: GeneralConfig) -> Self {
        Self {
            postgres_config: value.postgres_config,
            api_config: value.api_config,
            contract_verifier: value.contract_verifier,
            circuit_breaker_config: value.circuit_breaker_config,
            mempool_config: value.mempool_config,
            operations_manager_config: value.operations_manager_config,
            state_keeper_config: value.state_keeper_config,
            house_keeper_config: value.house_keeper_config,
            proof_compressor_config: value.proof_compressor_config,
            prover_config: value.prover_config,
            prover_gateway: value.prover_gateway,
            witness_vector_generator: value.witness_vector_generator,
            prover_group_config: value.prover_group_config,
            witness_generator_config: value.witness_generator_config,
            prometheus_config: value.prometheus_config,
            proof_data_handler_config: value.proof_data_handler_config,
            db_config: value.db_config,
            eth: value.eth,
            snapshot_creator: value.snapshot_creator,
            observability: value.observability,
            da_dispatcher_config: value.da_dispatcher_config,
            protective_reads_writer_config: value.protective_reads_writer_config,
            basic_witness_input_producer_config: value.basic_witness_input_producer_config,
            commitment_generator: value.commitment_generator,
            snapshot_recovery: value.snapshot_recovery,
            pruning: value.pruning,
            core_object_store: value.core_object_store,
            base_token_adjuster: value.base_token_adjuster,
            external_price_api_client_config: value.external_price_api_client_config,
            consensus_config: value.consensus_config,
            external_proof_integration_api_config: value.external_proof_integration_api_config,
            experimental_vm_config: value.experimental_vm_config,
            prover_job_monitor_config: value.prover_job_monitor_config,
            // VIA specific configs
            via_btc_sender_config: None,
            via_btc_watch_config: None,
            via_celestia_config: None,
            via_verifier_config: None,
        }
    }
}
