__imports__ = [
    "base",
    "l2-inits/via_coordinator.init.env",
    "configs/via_base.toml",
]

[via_verifier]
# Interval between polling db for verification requests (in ms).
poll_interval = 10000
# Coordinator server port.
port = 6060
# Coordinator server url.
url = "http://0.0.0.0:6060"
# The signer private key.
private_key = "cRaUbRSn8P8cXUcg6cMZ7oTZ1wbDjktYTsbdGw62tuqqD9ttQWMm"
# The verifiers public keys.
verifiers_pub_keys_str = [
    "03d8e2443ef58aa80fb6256bf3b94d2ecf9117f19cb17661ec60ad35fd84ff4a8b",
    "02043f839b8ecd9ffd79f26ec7d05750555cd0d1e0777cfc84a29b7e38e6324662",
]
# The bridge address. Run the following cmd: `cargo run --example key_generation_setup coordinator 03d8e2443ef58aa80fb6256bf3b94d2ecf9117f19cb17661ec60ad35fd84ff4a8b 02043f839b8ecd9ffd79f26ec7d05750555cd0d1e0777cfc84a29b7e38e6324662`
bridge_address_str = "bcrt1paf9ewekz080f4vluhm0sau7wn3f7uuxcngh9ffyram4q7qjsx4cqsa23tj"
# The minimum required signers.
required_signers = 2
# The verifier_mode can be simple verifier or coordinator.
verifier_mode = "COORDINATOR"

[via_btc_watch]
actor_role = "Verifier"
# Number of blocks that we should check when restarting the service.
btc_blocks_lag = 1000
