[package]
name = "via_verifier_coordinator"
description = "Via verifier coordinator"
version.workspace = true
edition.workspace = true
authors = ["Via Network"]


[dependencies]
hex.workspace = true
uuid = { version = "1.3", features = ["v4"] }
zksync_config.workspace = true
via_verifier_dal.workspace = true
zksync_utils.workspace = true
zksync_types.workspace = true
vise.workspace = true
via_btc_client.workspace = true
via_musig2.workspace = true
reqwest.workspace = true
via_withdrawal_client.workspace = true
via_verifier_types.workspace = true
via_verifier_state.workspace = true

anyhow.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["time"] }
tower-http = { workspace = true, features = ["cors", "timeout"] }
tower = { workspace = true }
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
bitcoin.workspace = true
secp256k1_musig2 = { package = "secp256k1", version = "0.30.0", features = [
    "rand",
] }
musig2 = "0.2.0"
base64 = "0.21"
thiserror = "1.0.57"
sha2.workspace = true
chrono.workspace = true
bincode = "1.3"
indexmap = "2.2"

[dev-dependencies]
