[rust]
log = """\
warn,\
zksync_node_framework=info,\
zksync_node_consensus=info,\
zksync_consensus_bft=info,\
zksync_consensus_network=info,\
zksync_consensus_storage=info,\
zksync_commitment_generator=info,\
zksync_core=debug,\
zksync_dal=info,\
zksync_db_connection=info,\
zksync_health_check=debug,\
zksync_eth_client=info,\
zksync_state_keeper=info,\
zksync_node_sync=info,\
zksync_storage=info,\
zksync_metadata_calculator=info,\
zksync_merkle_tree=info,\
zksync_node_api_server=info,\
zksync_node_db_pruner=info,\
zksync_reorg_detector=info,\
zksync_consistency_checker=info,\
zksync_state=debug,\
zksync_utils=debug,\
zksync_types=info,\
zksync_web3_decl=debug,\
loadnext=info,\
vm=info,\
zksync_external_node=info,\
zksync_snapshots_applier=debug,\
via_btc_watch=debug,\
via_state_keeper=debug,\
via_btc_sender=info,\
via_da_dispatcher=debug,\
via_da_clients=debug,\
via_zk_verifier=info,\
via_musig2=info,\
via_verifier_coordinator=info,\
via_verifier_btc_sender=info,\
via_verifier_btc_watch=info,\
via_verifier_dal=info,\
via_indexer=info,\
via_main_node_reorg_detector=info,\
via_verifier_reorg_detector=info,\
via_verifier_block_reverter=info,\
via_verifier_storage_init=info,\
"""
